### ISSUE TITLE
Error when exporting .mat file for  "Closed Region" spline.

### ISSUE THREAD

**Issue by iverzh** [denseanalysis/denseanalysis#26]
Hello!

When exporting the .mat file for a closed region ROI, I get the following error. Before exporting, displacement data is viewable, but strain data is not. Thank you again for your help!

> Undefined function or variable 'wbar'.
> Error in meshfaces (line 127)
>    close(wbar);
> Error in spl2strain>spl2patchGeneral (line 161)
>     [v,f,id] = meshfaces(C,edge,face,optA,optB);
> Error in spl2strain (line 54)
>             fv = spl2patchGeneral(api);
> Error in AnalysisViewer>spl2strainFcn (line 2307)
>     data = spl2strain(api);
> Error in AnalysisViewer>fvDisplay/initFcn (line 1309)
>             spl2strainFcn(obj);
> Error in AnalysisViewer>switchstate (line 460)
>         api.initFcn();
> Error in AnalysisViewer>@(src,evnt)switchstate(obj,evnt) (line 309)
>         'SelectionChangeFcn',   @(src,evnt)switchstate(obj,evnt),...
> Error while evaluating ButtonGroup SelectionChangedFcn

**Comment by suever** [comment]
@ilyaver This is on R2015b?

**Comment by suever** [comment]
@ilyaver There were some issues in the Mesh2d library from the file exchange that I had to fix to deal with this. I have updated the code within this project and hopefully it will work for you now. Let me know if you have any issues with this fix.
