### ISSUE TITLE
Motion Guided Segmentation Plugin

### ISSUE THREAD

**Issue by rmagrath3** [denseanalysis/denseanalysis#30]
I'm seeing this error when trying motion guided segmentation on 3D encoded data. The same datasets, with only X and Y data loaded into the workspace, work fine. 

> "Motion Guided Segmentation Plugin failed to complete
> 
> ERROR: The ROI sequence indices [57,58,59,60] do not match the DENSE sequence indices [1/2, 1/3, 1/4] "

I can send over a sample workspace if that helps.

**Comment by suever** [comment]
@rmagrath3  Sorry, just getting around to cleaning some things up on this project. Any chance you can send that workspace so I can take a look?

**Comment by rmagrath3** [comment]
It's been a while and I'm not quite sure where it is. If I remember correctly I played with a line or two of code and that fixed it, but let me try to re-trace my steps. If I can create the error again I will send it over.

**Comment by suever** [comment]
@rmagrath3  I think I found the issue. I'll send you the updated plugin. I'm 100% certain that it should fix this bug so I'll go ahead and close this out.
