### ISSUE TITLE
Movie export doesn't work

### ISSUE THREAD

**Issue by andydscott** [denseanalysis/denseanalysis#52]
When trying to export movies (OS X, Matlab 2019a) the code gives an error due to the 'hardcopy' function which was removed from Matlab.  There is a quick fix using 'getframe'.

**Comment by andydscott** [comment]
<img width="729" alt="Screenshot 2020-10-06 at 14 14 42" src="https://user-images.githubusercontent.com/17884953/95206206-50859d00-07de-11eb-9e75-7dedd71406b2.png">

**Comment by suever** [comment]
Thanks for reporting this @andydscott! The fix should be incorporated in the latest release, v0.5.2
